name: Add File and Display Folder Contents

on:
  push:
    branches:
      - main  # or your preferred branch

jobs:
  add-file-and-display:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    steps:
    -uses: 
        with:
            #token: ${{ secrets.ACCESS_TOKEN }} 
          path: my-submodule
          ref: main
          pr_branch: main 
          target_branch: main

    - name: Checkout repository again
      uses: actions/checkout@v4.1.1
      with:
        ref: main

    - name: Display folder contents
      run: ls
