name: Add File and Display Folder Contents

on:
  push:
    branches:
      - main  # or your preferred branch
  workflow_dispatch:

jobs:
  add-file-and-display:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    steps:
    - name: Checkout repository
      uses: mheap/submodule-sync-action@v1
      with:
        path: my-submodule  # Specify the path if you want to checkout to a specific folder
        token: ${{ secrets.ACCESS }}
        ref: main
        pr_branch: main  # This is not a valid input for actions/checkout. Remove it.
        target_branch: main  # This is not a valid input for actions/checkout. Remove it.
        base_branch: main

    - name: Checkout repository again
      uses: actions/checkout@v4.1.1
      with:
        ref: main
        submodules: true

    - name: Display folder contents
      run: |
          cd my-submodule
          ls

