name: Add File and Display Folder Contents

on:
  push:
    branches:
      - main  # or your preferred branch

jobs:
  add-file-and-display:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Add file and commit
      run: |
        echo "Content to be added" > new_file.txt
        git add new_file.txt
        git commit -m "Add new_file.txt"
        git push

    - name: Checkout repository again
      uses: actions/checkout@v2

    - name: Display folder contents
      run: ls
