name: Add File and Display Folder Contents

on:
  push:
    branches:
      - main  # or your preferred branch

jobs:
  add-file-and-display:
    runs-on: ubuntu-latest
    permissions: write

    steps:
    - uses: actions/checkout@v4
    - run: |
          echo "Content to be added" > new_file.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push

    - name: Checkout repository again
      uses: actions/checkout@v2

    - name: Display folder contents
      run: ls
