name: Add File and Display Folder Contents

on:
  push:
    branches:
      - main  # or your preferred branch

jobs:
  add-file-and-display:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        path: my-submodule  # Specify the path if you want to checkout to a specific folder
        ref: main
        pr_branch: main  # This is not a valid input for actions/checkout. Remove it.
        target_branch: main  # This is not a valid input for actions/checkout. Remove it.

    - name: Checkout repository again
      uses: actions/checkout@v4.1.1
      with:
        ref: main

    - name: Display folder contents
      run: ls

